import { initSite } from './site.js';
import { initJourney } from './journey.js';
import { initAnatomy } from './anatomy.js';
import { initBeans } from './beans.js';
import { initMap } from './map.js';
import { initRoast } from './roast.js';
import { initGrind } from './grind.js';
import { initWheel } from './wheel.js';
import { initBarista } from './barista.js';
import { initPour } from './pour.js';
import { initGuide } from './guide.js';

initSite();
initJourney();
initAnatomy();
initBeans();
initMap();
initRoast();
initGrind();
initWheel();
initBarista();
initPour();
initGuide();
