// Everything outside the cup: the farm-to-cup journey, species, roasts, origins, grind sizes, flavors.
// Numbers are rounded, typical values. Farms, roasters and cafés all vary.

// ---------- 01 · Seed to cup ----------
// phase groups the steps on the timeline; art picks the drawing in journey.js
export const PHASES = ['Farm', 'Mill', 'Export', 'Roaster', 'Your kitchen'];

export const JOURNEY = [
  { id: 'plant', phase: 'Farm', art: 'seedling', title: 'Plant', time: '3–4 years to first crop',
    text: 'A coffee tree starts as a seed, still in its parchment, planted in a nursery bag. After about a year in the shade it moves out to the farm, then needs another few years before it bears real fruit.',
    points: ['Grows best in the “bean belt” between the tropics', 'Arabica likes altitude: roughly 600–2,200 m', 'One tree gives about half a kilo of roasted coffee a year'],
    fact: 'Most of the world’s Arabica descends from a handful of trees taken out of Ethiopia and Yemen.' },
  { id: 'flower', phase: 'Farm', art: 'flower', title: 'Flower', time: 'A few days',
    text: 'After the first heavy rain of the season the whole farm blooms at once. The small white flowers smell like jasmine and fall off within days.',
    points: ['Arabica flowers pollinate themselves', 'Robusta needs bees and wind to cross-pollinate', 'Each flower that takes becomes one cherry'],
    fact: 'Farmers call a full bloom “coffee snow” because the hills turn white.' },
  { id: 'ripen', phase: 'Farm', art: 'ripen', title: 'Ripen', time: '6–9 months',
    text: 'Clusters of green cherries swell along the branches and slowly turn yellow, then red. They don’t all ripen together, so one branch can hold every color at once.',
    points: ['Most varieties ripen red, some yellow, orange or pink', 'Higher and cooler means slower ripening and more sugar', 'Robusta takes even longer, up to 11 months'],
    fact: 'Pickers taste the cherries. Ripe ones are sweet, like a cross between a grape and a cranberry.' },
  { id: 'harvest', phase: 'Farm', art: 'harvest', title: 'Harvest', time: 'Once or twice a year',
    text: 'There are two ways to pick. Selective picking means hand-picking only the ripe cherries and going back to the same tree again and again. Strip picking pulls everything off the branch at once, by hand or by machine.',
    points: ['Selective: slower and pricier, better coffee', 'Strip: fast and common on big flat farms (like much of Brazil)', 'A good picker gathers about 45–90 kg of cherries a day'],
    fact: 'Only about a fifth of a cherry’s weight ends up as green coffee.' },
  { id: 'separate', phase: 'Mill', art: 'float', title: 'Float & sort', time: 'Same day',
    text: 'Cherries get dumped into water. Ripe, dense cherries sink. Underripe, damaged or bug-eaten ones float and are skimmed off. It’s the first quality check.',
    points: ['Water separation: ripe cherries sink', 'Floaters often become cheaper local coffee', 'Some mills also sort by size and density with machines'],
    fact: 'Processing has to start within hours, or the fruit begins to ferment on its own.' },
  { id: 'process', phase: 'Mill', art: 'process', title: 'Process', time: '1–3 days to start',
    text: 'This step changes the flavor more than almost anything else: how do you get the fruit off the seed? Pick a method to see what it does.',
    points: [], choice: true,
    fact: 'Newer “special processes” like anaerobic fermentation seal the cherries in tanks to push wild, fruity flavors.' },
  { id: 'dry', phase: 'Mill', art: 'dry', title: 'Dry', time: '1–4 weeks',
    text: 'The beans are spread on patios or raised beds and raked several times a day until they’re down to about 11% moisture. Some big mills use mechanical dryers with controlled heat and airflow.',
    points: ['Sun drying: traditional, slower, often more flavor', 'Mechanical drying: faster, works in the rainy season', 'Too wet and it molds. Too dry and it goes flat.'],
    fact: 'Workers cover the beans every time it rains, sometimes several times a day.' },
  { id: 'hull', phase: 'Mill', art: 'hull', title: 'Rest & hull', time: '1–2 months resting',
    text: 'The dried coffee rests in its parchment for a month or two so the moisture evens out. Then a huller cracks off the dried fruit or parchment and reveals the green bean.',
    points: ['Dry hulling: removes the dried fruit layer', 'Wet hulling: hulled while still damp (common in Sumatra, gives earthy flavors)', 'Polishing can take off the silver skin. It’s optional and mostly cosmetic.'],
    fact: 'Coffee keeps best “in parchment,” so many farms wait to hull until it’s sold.' },
  { id: 'sort', phase: 'Mill', art: 'sort', title: 'Clean, sort & grade', time: 'Days',
    text: 'Air blowers knock out dust, vibrating screens sort beans by size, and gravity tables sort them by weight. Optical sorters and people with sharp eyes pick out black, sour or broken beans.',
    points: ['Size is measured in 64ths of an inch (“screen 18” = 18/64″)', 'Heavier, denser beans usually taste better', 'Specialty coffee scores 80+ points out of 100 in a tasting called cupping'],
    fact: 'Moisture gets checked again before export, and it should be about 10–12%.' },
  { id: 'ship', phase: 'Export', art: 'ship', title: 'Pack & ship', time: '4–8 weeks',
    text: 'Green coffee goes into 60–70 kg jute sacks, often with a plastic liner to keep it fresh, or into vacuum bags for the fanciest lots. Then it rides in a shipping container to roasters around the world.',
    points: ['One container holds about 300 sacks', 'Green coffee keeps for months if it stays cool and dry', 'It’s one of the most traded farm products on Earth'],
    fact: 'Green coffee barely smells like coffee. All the familiar aroma comes from roasting.' },
  { id: 'roast', phase: 'Roaster', art: 'roast', title: 'Roast', time: '8–15 minutes',
    text: 'In a drum roaster the beans dry, turn yellow, brown, then crack like popcorn. The roaster decides how far to go, from light and fruity to dark and smoky.',
    points: ['First crack around 196 °C means the beans are drinkable', 'Beans lose 12–20% of their weight, mostly water', 'Over 800 aroma compounds form'],
    fact: 'Try it yourself in the Roastery further down.', link: '#roast' },
  { id: 'rest', phase: 'Roaster', art: 'bag', title: 'Rest & bag', time: '3–14 days',
    text: 'Fresh beans are full of carbon dioxide. Bags get a one-way valve so the gas can get out but air can’t get in. Most coffee tastes best a week or two after roasting.',
    points: ['Too fresh tastes gassy and sharp', 'Peak for filter: roughly 4–30 days', 'Store beans airtight, away from light and heat, not in the fridge'],
    fact: 'Squeeze a bag and sniff the valve. That puff is the CO₂ escaping.' },
  { id: 'grind', phase: 'Your kitchen', art: 'grind', title: 'Grind', time: 'Seconds',
    text: 'Grinding opens up the bean so water can reach the flavor. Match the size to your brewer: fine for espresso, coarse for French press.',
    points: ['Grind right before brewing, because aroma fades within minutes', 'Burr grinders give even pieces, blade grinders don’t', 'See the Grind Guide below'],
    fact: 'Ground coffee has about 10,000× the surface area of whole beans.', link: '#grind' },
  { id: 'brew', phase: 'Your kitchen', art: 'brew', title: 'Brew', time: '30 s to 24 h',
    text: 'Hot water (about 90–96 °C) pulls out the flavors. Espresso does it under pressure in under 30 seconds. Cold brew takes most of a day.',
    points: ['Filter: about 1 g coffee to 16 g water', 'Espresso: about 1 g coffee to 2 g out, in 25–30 s', 'Too sour? Grind finer. Too bitter? Grind coarser.'],
    fact: 'Brewed coffee is about 98.5% water, so good water matters.' },
  { id: 'sip', phase: 'Your kitchen', art: 'cup', title: 'Sip', time: 'Take your time',
    text: 'Years of growing and dozens of hands later, here’s your cup. Slurp it, let it cool a little, and see what flavors show up. Coffee tastes sweeter as it cools.',
    points: ['Use the Flavor Wheel to name what you taste', 'Make your own drink in Barista School'],
    fact: '5 kg of ripe cherries → about 1 kg green coffee → about 850 g roasted → roughly 55 cups.', link: '#barista' },
];

export const PROCESSES = [
  { id: 'washed', name: 'Washed', aka: 'Wet process',
    how: 'A pulper strips the skin and fruit, the seeds ferment in water for 12–48 h to loosen the sticky mucilage, then get washed clean and dried.',
    taste: 'Clean, bright and crisp. You taste the bean and where it grew.', where: 'Colombia, Kenya, Central America' },
  { id: 'natural', name: 'Natural', aka: 'Dry process',
    how: 'The whole cherry dries in the sun for weeks with the fruit still on, then the dried husk is hulled off.',
    taste: 'Fruity, jammy and heavy. Blueberry and wine notes are common.', where: 'Ethiopia, Brazil, Yemen' },
  { id: 'honey', name: 'Honey', aka: 'Pulped natural',
    how: 'The skin comes off but some of the sticky mucilage stays on while it dries. More left on = “red” or “black” honey.',
    taste: 'Sweet and round, in between washed and natural.', where: 'Costa Rica, El Salvador, Brazil' },
];

// mass you’re left with at each step, out of 5 kg of ripe cherries
export const MASS_TRAIL = { harvest: 5, separate: 4.6, process: 2.2, dry: 1.25, hull: 1.0, sort: 0.95, roast: 0.82, sip: 0.82 };

// ---------- 03 · Species, varieties, roasts ----------
export const SPECIES = [
  { id: 'arabica', named: 'Named after Arabia. Coffee first grew wild in Ethiopia, but people in Yemen (on the Arabian Peninsula) were the first to farm it and ship it out through the port of Mocha. So when the botanist Carl Linnaeus named the plant in 1753, he named it after Arabia, where Europeans knew coffee from.', parents: 'Arabica is a natural cross of two other species, Robusta and Eugenioides. They met in the wild hundreds of thousands of years ago.',
    name: 'Arabica', sci: 'Coffea arabica', share: 58, caffeine: '1.2–1.5%', caffeineN: 1.35,
    altitude: '600–2,200 m', shape: 'Oval with a curvy S-shaped crease',
    taste: 'Sweet, bright and complex: fruit, flowers, chocolate, caramel.',
    grows: 'Brazil, Colombia, Ethiopia, Central America', used: 'Nearly all specialty coffee, plus Starbucks, Dunkin’ and Tim Hortons', price: 'Higher: lower yields and lots of care (pruning, shade, hand-picking)',
    notes: 'Delicate and fussy. It needs altitude and gets hit hard by leaf rust and heat.', color: '#7a4a2a', scale: 1 },
  { id: 'robusta', named: '“Robusta” means robust. A Belgian plant nursery sold it under that name around 1900 because it shrugged off the disease wiping out Arabica farms. Botanists call it Coffea canephora, from a Greek word for “basket-bearer.”',
    name: 'Robusta', sci: 'Coffea canephora', share: 40, caffeine: '2.2–2.7%', caffeineN: 2.45,
    altitude: '0–800 m', shape: 'Smaller and rounder with a straight crease',
    taste: 'Bold, bitter and earthy: dark chocolate, wood, peanut.',
    grows: 'Vietnam, Brazil, Indonesia, Uganda, India', used: 'Instant coffee, Italian espresso blends (for crema), cheaper blends', price: 'Lower: easy to grow, with big harvests',
    notes: 'Tough and productive. The extra caffeine works as a natural bug repellent.', color: '#5a3520', scale: 0.82 },
  { id: 'liberica', named: 'Named after Liberia in West Africa, where botanists first described it in the 1800s.',
    name: 'Liberica', sci: 'Coffea liberica', share: 1, caffeine: 'about like Arabica', caffeineN: 1.3,
    altitude: 'Low, hot lowlands', shape: 'Big and lopsided, almost teardrop',
    taste: 'Smoky and woody with a strange floral, jackfruit-like fruitiness.',
    grows: 'Philippines (“kapeng barako”), Malaysia, Indonesia', used: 'Kapeng barako in the Philippines, plus some instant coffee', price: 'Varies. It’s rare outside Southeast Asia',
    notes: 'Its trees grow up to 20 m tall. It got the Philippines through the 1890s rust outbreak.', color: '#6b3f22', scale: 1.35 },
  { id: 'excelsa', named: '“Excelsa” is Latin for tall or lofty, because the trees grow so big. It was named in 1905 by the French botanist Auguste Chevalier.',
    name: 'Excelsa', sci: 'C. liberica var. dewevrei', share: 1, caffeine: 'less than Robusta', caffeineN: 1.1,
    altitude: 'Low to mid', shape: 'Almond-shaped, smaller than Liberica',
    taste: 'Tart and fruity up front, dark and roasty at the finish.',
    grows: 'Vietnam, Philippines, India', used: 'Adding depth to blends, plus some instant coffee', price: 'Varies. It’s rare and mostly sold locally',
    notes: 'Scientists reclassified it as a kind of Liberica in 2006, but the coffee world still treats it separately.', color: '#62391f', scale: 1.1 },
];

// The coffees you see named on bags. id = map country (or dot for places too small to shade).
export const ORIGIN_REGIONS = ['Latin America', 'Africa', 'Asia & Pacific', 'Islands & Arabia'];
export const ORIGIN_COFFEES = [
  { name: 'Colombian', country: 'Colombia', id: 170, region: 'Latin America', species: 'Arabica', process: 'Washed',
    notes: ['Caramel', 'Chocolate', 'Nutty', 'Mild citrus'], bag: 'Supremo (biggest beans) and Excelso (a bit smaller) are size grades, not quality scores.',
    fact: 'Smooth body, balanced acidity, sweet. It works in every brewer: drip, pour-over, French press, espresso. Over half a million families grow it, mostly on small, steep Andes farms, and two harvests a year keep it in season.' },
  { name: 'Brazil Santos', country: 'Brazil', id: 76, region: 'Latin America', species: 'Arabica (+ Robusta)', process: 'Natural / pulped natural',
    notes: ['Chocolate', 'Peanut', 'Low acid', 'Heavy body'], bag: '“Santos” is the port it ships from, not a region.',
    fact: 'The backbone of most espresso blends. Smooth and nutty, and very forgiving in milk drinks.' },
  { name: 'Guatemala Antigua', country: 'Guatemala', id: 320, region: 'Latin America', species: 'Arabica', process: 'Washed',
    notes: ['Dark chocolate', 'Spice', 'Bright', 'Smoky'], bag: 'SHB means Strictly Hard Bean: grown high up, so the beans are dense.',
    fact: 'Antigua sits in a valley ringed by three volcanoes, and volcanic ash keeps the soil rich.' },
  { name: 'Costa Rica Tarrazú', country: 'Costa Rica', id: 188, region: 'Latin America', species: 'Arabica', process: 'Washed / honey',
    notes: ['Citrus', 'Honey', 'Clean', 'Bright'], bag: 'Look for “honey process” for a sweeter, rounder cup.',
    fact: 'Costa Rica made honey processing famous with its “micro-mills”: tiny farm-level mills that process each lot by hand.' },
  { name: 'Mexican', country: 'Mexico', id: 484, region: 'Latin America', species: 'Arabica', process: 'Washed',
    notes: ['Light', 'Nutty', 'Cocoa', 'Mild'], bag: '“Altura” means high-grown. Chiapas and Oaxaca are the big names.',
    fact: 'One of the largest sources of organic coffee in the world.' },
  { name: 'Peruvian', country: 'Peru', id: 604, region: 'Latin America', species: 'Arabica', process: 'Washed',
    notes: ['Sweet', 'Nutty', 'Soft', 'Milk chocolate'], bag: 'Often labeled organic and Fairtrade.',
    fact: 'Mostly grown by small farmers high in the Andes and Amazon cloud forest.' },
  { name: 'Honduran', country: 'Honduras', id: 340, region: 'Latin America', species: 'Arabica', process: 'Washed',
    notes: ['Caramel', 'Stone fruit', 'Sweet'], bag: 'Marcala was the country’s first protected coffee region.',
    fact: 'Central America’s biggest producer, though it was long sold anonymously in blends.' },
  { name: 'Panama Geisha', country: 'Panama', id: 591, region: 'Latin America', species: 'Arabica', process: 'Washed / natural',
    notes: ['Jasmine', 'Bergamot', 'Peach', 'Tea-like'], bag: 'Often sold by the farm name, like Hacienda La Esmeralda.',
    fact: 'The most expensive coffee at auction. Some lots have sold for thousands of dollars per kilo.' },
  { name: 'Ethiopian Yirgacheffe', country: 'Ethiopia', id: 231, region: 'Africa', species: 'Arabica (heirloom)', process: 'Washed',
    notes: ['Jasmine', 'Lemon', 'Bergamot', 'Tea-like'], bag: 'Grade 1 (G1) is the cleanest, best-sorted lot.',
    fact: 'Many people’s “wait, coffee can taste like this?” moment. Light and floral, almost like tea.' },
  { name: 'Ethiopian Harrar', country: 'Ethiopia', id: 231, region: 'Africa', species: 'Arabica (heirloom)', process: 'Natural',
    notes: ['Blueberry', 'Wine', 'Dark chocolate', 'Spice'], bag: 'Also look for Guji and Sidamo naturals, which taste similar.',
    fact: 'Dried in the whole cherry under the sun the old way, so it tastes wild and fruity.' },
  { name: 'Kenya AA', country: 'Kenya', id: 404, region: 'Africa', species: 'Arabica (SL28, SL34)', process: 'Washed',
    notes: ['Blackcurrant', 'Grapefruit', 'Tomato', 'Juicy'], bag: 'AA is the biggest bean size. AB is a little smaller, and the flavor is often just as good.',
    fact: 'Kenyan coffee is often washed twice and soaked, which gives it that bright, juicy, almost savory snap.' },
  { name: 'Tanzanian Peaberry', country: 'Tanzania', id: 834, region: 'Africa', species: 'Arabica', process: 'Washed',
    notes: ['Bright', 'Citrus', 'Black tea'], bag: '“PB” on the bag means peaberry: one round bean per cherry.',
    fact: 'Grown on the slopes of Kilimanjaro and Mount Meru. Peaberries are sorted out by hand and screen.' },
  { name: 'Rwandan', country: 'Rwanda', id: 646, region: 'Africa', species: 'Arabica (Bourbon)', process: 'Washed',
    notes: ['Red fruit', 'Floral', 'Black tea', 'Sweet'], bag: 'Usually named after the washing station that processed it.',
    fact: 'Almost all of it is Bourbon, grown on small farms in the “land of a thousand hills.”' },
  { name: 'Sumatra Mandheling', country: 'Indonesia', id: 360, region: 'Asia & Pacific', species: 'Arabica', process: 'Wet-hulled',
    notes: ['Earthy', 'Cedar', 'Herbal', 'Low acid'], bag: 'Named after the Mandailing people of North Sumatra.',
    fact: 'Wet-hulling (“giling basah”) strips the parchment while the beans are still damp, which gives that deep, earthy flavor.' },
  { name: 'Java', country: 'Indonesia', id: 360, region: 'Asia & Pacific', species: 'Arabica (+ Robusta)', process: 'Washed',
    notes: ['Earthy', 'Spicy', 'Syrupy', 'Low acid'], bag: '“Mocha Java” is the oldest known blend: Yemen + Java.',
    fact: 'The Dutch planted coffee here in the 1690s. It became so common that “java” turned into slang for coffee.' },
  { name: 'Vietnamese', country: 'Vietnam', id: 704, region: 'Asia & Pacific', species: 'Mostly Robusta', process: 'Natural',
    notes: ['Bold', 'Dark chocolate', 'Bitter', 'Woody'], bag: 'Central Highlands (Buôn Ma Thuột) grows most of it.',
    fact: 'Brewed strong through a little metal phin filter over sweetened condensed milk: cà phê sữa đá.' },
  { name: 'Monsooned Malabar', country: 'India', id: 356, region: 'Asia & Pacific', species: 'Arabica', process: 'Natural, then monsooned',
    notes: ['Mellow', 'Spicy', 'Woody', 'Very low acid'], bag: 'The beans look pale and puffy. That’s normal!',
    fact: 'The green beans sit in open warehouses through the monsoon winds for months, copying how coffee aged on old sailing ships.' },
  { name: 'Papua New Guinea', country: 'Papua New Guinea', id: 598, region: 'Asia & Pacific', species: 'Arabica', process: 'Washed',
    notes: ['Sweet', 'Tropical fruit', 'Earthy'], bag: 'Highland names like Sigri or Waghi.',
    fact: 'Most of it is grown in small village gardens, not big estates.' },
  { name: 'Jamaica Blue Mountain', country: 'Jamaica', id: 388, region: 'Islands & Arabia', species: 'Arabica (Typica)', process: 'Washed',
    notes: ['Mild', 'Smooth', 'Sweet', 'Clean'], bag: 'A protected name. Real Blue Mountain is certified and often sold in little wooden barrels.',
    fact: 'Most of the crop goes to Japan.' },
  { name: 'Hawaiian Kona', country: 'Hawaii, USA', dot: 0, region: 'Islands & Arabia', species: 'Arabica (Typica)', process: 'Washed',
    notes: ['Smooth', 'Nutty', 'Brown sugar', 'Bright'], bag: 'Careful: a “Kona blend” only has to be 10% Kona.',
    fact: 'Grown on the slopes of the Hualālai and Mauna Loa volcanoes on the Big Island.' },
  { name: 'Yemen Mocha', country: 'Yemen', id: 887, region: 'Islands & Arabia', species: 'Arabica', process: 'Natural',
    notes: ['Wine', 'Dried fruit', 'Spice', 'Chocolate'], bag: 'Look for regions like Haraz or Bani Matar.',
    fact: 'The port of Mocha shipped the world’s coffee for centuries, and the chocolatey taste is why the mocha drink got its name.' },
];

// Coffee plants you’ll rarely (or never) see in a café. Over 130 Coffea species exist.
export const RARE_SPECIES = [
  { name: 'Eugenioides', sci: 'Coffea eugenioides', named: 'Means “looks like Eugenia,” a plant it resembles.',
    note: 'One of Arabica’s two parents. Very low caffeine and naturally sweet, and a few Colombian farms now grow it for specialty coffee.' },
  { name: 'Stenophylla', sci: 'Coffea stenophylla', named: 'Greek for “narrow leaf.”',
    note: 'A wild coffee from Sierra Leone, rediscovered in 2020. It tastes a lot like Arabica but handles heat far better, which makes it a big hope as the climate warms.' },
  { name: 'Racemosa', sci: 'Coffea racemosa', named: 'Latin for “in clusters.”',
    note: 'Grows along the coast of Mozambique. Small beans with very little caffeine, and tough enough for dry, hot weather.' },
  { name: 'Charrieriana', sci: 'Coffea charrieriana', named: 'Named after André Charrier, a French coffee scientist.',
    note: 'Found in Cameroon. It’s one of the only coffee plants with no caffeine at all.' },
];

// Cherry color by variety. Mostly Arabica.
// family groups them by their family tree
export const VARIETY_FAMILIES = ['Typica', 'Bourbon', 'Ethiopian', 'Hybrid', 'Robusta'];
export const VARIETIES = [
  { name: 'Typica', family: 'Typica', color: '#a91d2a', from: 'Yemen → Java → the world', note: 'One of the two original lines that left Yemen. Clean and sweet, but low-yielding.' },
  { name: 'Blue Mountain', family: 'Typica', color: '#b0222f', from: 'Jamaica', note: 'A Typica grown in Jamaica’s Blue Mountains. Mild, smooth and pricey.' },
  { name: 'Kona', family: 'Typica', color: '#b8202e', from: 'Hawaii', note: 'Typica grown on the slopes of a volcano. Hawaii’s most famous crop after pineapple.' },
  { name: 'Maragogype', family: 'Typica', color: '#c42a3a', from: 'Brazil', note: 'Nicknamed the “elephant bean.” A Typica mutation with some of the biggest beans around.' },
  { name: 'Red Bourbon', family: 'Bourbon', color: '#b8202e', from: 'Réunion island', note: 'The other original line, named after the island once called Bourbon. Sweet and caramel-y.' },
  { name: 'Yellow Bourbon', family: 'Bourbon', color: '#e8b923', from: 'Brazil', note: 'Ripens yellow instead of red. Very sweet, popular in Brazil.' },
  { name: 'Pink Bourbon', family: 'Bourbon', color: '#e77a8e', from: 'Colombia', note: 'A pink-ripening Colombian star with floral, fruity cups.' },
  { name: 'Orange Bourbon', family: 'Bourbon', color: '#e8812b', from: 'Central America', note: 'A rare natural cross that ripens orange.' },
  { name: 'Caturra', family: 'Bourbon', color: '#b31e2b', from: 'Brazil', note: 'A dwarf Bourbon. Short trees mean more plants per hill and easier picking.' },
  { name: 'Catuaí', family: 'Bourbon', color: '#e2a91f', from: 'Brazil', note: 'Caturra crossed with Mundo Novo. Comes in red and yellow. A workhorse in Brazil and Central America.' },
  { name: 'Mundo Novo', family: 'Bourbon', color: '#a91d2a', from: 'Brazil', note: '“New World.” A natural cross of Typica and Bourbon. Tall, strong and productive.' },
  { name: 'Pacamara', family: 'Bourbon', color: '#bf2433', from: 'El Salvador', note: 'Pacas (a dwarf Bourbon) crossed with giant Maragogype. Huge beans, wild flavors.' },
  { name: 'SL28', family: 'Bourbon', color: '#9c1b28', from: 'Kenya', note: 'Bred by Scott Laboratories in the 1930s. Famous for blackcurrant and bright, juicy acidity.' },
  { name: 'Geisha', family: 'Ethiopian', color: '#c42a3a', from: 'Ethiopia → Panama', note: 'From the Gesha forest in Ethiopia. Panama made it famous: jasmine, bergamot and record prices.' },
  { name: 'Ethiopian heirloom', family: 'Ethiopian', color: '#b8202e', from: 'Ethiopia', note: 'Thousands of wild and local types that were never named one by one. Blueberry, lemon and flowers.' },
  { name: 'Timor Hybrid', family: 'Hybrid', color: '#a01c28', from: 'East Timor', note: 'A natural cross of Arabica and Robusta found in the 1920s. It carries Robusta’s rust resistance.' },
  { name: 'Catimor', family: 'Hybrid', color: '#b8202e', from: 'Portugal (bred)', note: 'Caturra crossed with Timor Hybrid. Fights leaf rust, but the cup can be a bit flat.' },
  { name: 'Castillo', family: 'Hybrid', color: '#b31e2b', from: 'Colombia', note: 'Bred in Colombia to resist rust. Now covers a big share of Colombia’s farms.' },
  { name: 'Robusta', family: 'Robusta', color: '#8f1a25', from: 'Central & West Africa', note: 'Grows in tight clusters and ripens slowly. Most of Vietnam’s crop.' },
  { name: 'Conilon', family: 'Robusta', color: '#9a1c27', from: 'Brazil', note: 'Brazil’s kind of Robusta, grown mostly in Espírito Santo and Rondônia.' },
];

// The four roast levels in the photo, plus the bean sheen and names you’ll see on bags.
export const ROAST_LEVELS = [
  { id: 'light', name: 'Light', color: '#8a5631', crease: '#c19a6b', sheen: 0, temp: '196–205 °C', crack: 'Just past first crack',
    aka: 'Cinnamon, City, New England, Nordic', surface: 'Dry and matte',
    taste: 'Bright, fruity, floral, tea-like. You taste where it grew.', acidity: 5, body: 2, bitter: 1,
    brew: 'Pour-over, AeroPress' },
  { id: 'medium', name: 'Medium', color: '#64391f', crease: '#9a6a44', sheen: 0.1, temp: '210–220 °C', crack: 'Between the cracks',
    aka: 'City+, American, Breakfast', surface: 'Dry, maybe a faint sheen',
    taste: 'Balanced and sweet: caramel, nuts, milk chocolate.', acidity: 3.5, body: 3, bitter: 2.5,
    brew: 'Drip, pour-over, cold brew' },
  { id: 'mediumdark', name: 'Medium-Dark', color: '#3f2213', crease: '#6e4428', sheen: 0.3, temp: '222–230 °C', crack: 'Start of second crack',
    aka: 'Full City, Vienna', surface: 'Spots of oil',
    taste: 'Bittersweet: dark chocolate, spice, a little smoke.', acidity: 2, body: 4.5, bitter: 3.5,
    brew: 'Espresso, moka pot, French press' },
  { id: 'dark', name: 'Dark', color: '#24130a', crease: '#4a2c19', sheen: 0.6, temp: '235–245 °C', crack: 'Well into second crack',
    aka: 'French, Italian, Espresso roast', surface: 'Shiny and oily',
    taste: 'Smoky, roasty, heavy. The roast flavor covers the origin.', acidity: 1, body: 4, bitter: 5,
    brew: 'Espresso, milk drinks' },
];

// ---------- 04 · Map ----------
// ISO 3166 numeric ids (as used by the world-atlas TopoJSON).
// bags = rough recent harvest, millions of 60-kg bags. type: A = Arabica, R = Robusta.
export const PRODUCERS = [
  { id: 76,  name: 'Brazil',        bags: 66,  type: 'A + R', harvest: 'May–Sep', notes: 'Chocolate, nuts, low acidity', fact: 'Grows about a third of the world’s coffee, much of it machine-picked on huge flat farms.' },
  { id: 704, name: 'Vietnam',       bags: 28,  type: 'Mostly R', harvest: 'Oct–Jan', notes: 'Bold, bitter, dark chocolate', fact: 'The Robusta superpower. Try cà phê sữa đá: strong drip coffee over condensed milk and ice.' },
  { id: 170, name: 'Colombia',      bags: 12.5,type: 'A', harvest: 'Two harvests a year', notes: 'Caramel, red fruit, balanced', fact: 'All Arabica, nearly all hand-picked on steep Andes slopes.' },
  { id: 360, name: 'Indonesia',     bags: 10,  type: 'A + R', harvest: 'Apr–Sep', notes: 'Earthy, herbal, heavy body', fact: 'Sumatra’s wet-hulling gives its famously earthy flavor. Java gave coffee one of its nicknames.' },
  { id: 231, name: 'Ethiopia',      bags: 8.5, type: 'A', harvest: 'Oct–Jan', notes: 'Blueberry, jasmine, lemon', fact: 'Where Arabica comes from. Wild coffee still grows in its forests, and half the crop is drunk at home.' },
  { id: 800, name: 'Uganda',        bags: 6.5, type: 'Mostly R', harvest: 'Year-round', notes: 'Chocolate, spice', fact: 'Africa’s biggest exporter. Robusta grows wild here.' },
  { id: 356, name: 'India',         bags: 6,   type: 'A + R', harvest: 'Nov–Feb', notes: 'Spicy, low acid', fact: '“Monsooned Malabar” beans are left out in monsoon winds to swell and mellow.' },
  { id: 340, name: 'Honduras',      bags: 5.5, type: 'A', harvest: 'Nov–Apr', notes: 'Caramel, stone fruit', fact: 'Central America’s biggest producer.' },
  { id: 604, name: 'Peru',          bags: 4,   type: 'A', harvest: 'May–Sep', notes: 'Mild, sweet, nutty', fact: 'One of the largest suppliers of organic and Fairtrade coffee.' },
  { id: 484, name: 'Mexico',        bags: 4,   type: 'A', harvest: 'Nov–Mar', notes: 'Light, nutty, cocoa', fact: 'Chiapas, Veracruz and Oaxaca grow most of it, a lot on small family plots.' },
  { id: 320, name: 'Guatemala',     bags: 3.5, type: 'A', harvest: 'Dec–Mar', notes: 'Chocolate, spice, bright', fact: 'Antigua’s volcanic soil is famous among roasters.' },
  { id: 558, name: 'Nicaragua',     bags: 2.7, type: 'A', harvest: 'Nov–Mar', notes: 'Sweet, nutty, mild', fact: 'Mostly shade-grown under forest trees.' },
  { id: 156, name: 'China',         bags: 1.8, type: 'A', harvest: 'Nov–Mar', notes: 'Mild, sweet', fact: 'Almost all of it comes from Yunnan province, near Myanmar and Laos.' },
  { id: 188, name: 'Costa Rica',    bags: 1.3, type: 'A', harvest: 'Nov–Mar', notes: 'Bright, honeyed, clean', fact: 'Planting Robusta has been heavily restricted here for decades.' },
  { id: 834, name: 'Tanzania',      bags: 1.2, type: 'A + R', harvest: 'Jul–Dec', notes: 'Bright, blackcurrant', fact: 'Coffee grows on the slopes of Kilimanjaro.' },
  { id: 384, name: 'Côte d’Ivoire', bags: 1,   type: 'R', harvest: 'Nov–Mar', notes: 'Bold, earthy', fact: 'Was once one of the top three producers in the world.' },
  { id: 404, name: 'Kenya',         bags: 0.8, type: 'A', harvest: 'Oct–Dec', notes: 'Blackcurrant, grapefruit, juicy', fact: 'Its SL28 and SL34 varieties are famous for their bright, juicy acidity.' },
  { id: 598, name: 'Papua New Guinea', bags: 0.8, type: 'A', harvest: 'Apr–Sep', notes: 'Sweet, fruity, earthy', fact: 'Much of it is grown in village gardens in the highlands.' },
  { id: 764, name: 'Thailand',      bags: 0.6, type: 'Mostly R', harvest: 'Nov–Feb', notes: 'Earthy, nutty', fact: 'Northern hill tribes swapped opium poppies for coffee.' },
  { id: 222, name: 'El Salvador',   bags: 0.6, type: 'A', harvest: 'Nov–Mar', notes: 'Sweet, chocolate, citrus', fact: 'Bred the big-bean Pacamara variety.' },
  { id: 218, name: 'Ecuador',       bags: 0.5, type: 'A + R', harvest: 'May–Sep', notes: 'Floral, sweet', fact: 'Grows coffee in both the Andes and the lowlands.' },
  { id: 862, name: 'Venezuela',     bags: 0.5, type: 'A', harvest: 'Oct–Feb', notes: 'Sweet, mild', fact: 'Used to be a major exporter in the 1800s.' },
  { id: 214, name: 'Dominican Rep.',bags: 0.4, type: 'A', harvest: 'Sep–Apr', notes: 'Chocolate, mild', fact: 'Most of the crop gets drunk at home.' },
  { id: 120, name: 'Cameroon',      bags: 0.4, type: 'A + R', harvest: 'Oct–Feb', notes: 'Earthy, bold', fact: 'Grows both species on volcanic highlands.' },
  { id: 608, name: 'Philippines',   bags: 0.4, type: 'R + Liberica', harvest: 'Nov–Mar', notes: 'Smoky, bold', fact: 'Home of kapeng barako, a strong Liberica coffee.' },
  { id: 646, name: 'Rwanda',        bags: 0.3, type: 'A', harvest: 'Mar–Jul', notes: 'Red fruit, floral, tea', fact: 'Coffee washing stations helped rebuild rural income after 1994.' },
  { id: 180, name: 'DR Congo',      bags: 0.3, type: 'A + R', harvest: 'Year-round', notes: 'Fruity, bright', fact: 'Kivu’s lake-side highlands are a rising specialty origin.' },
  { id: 108, name: 'Burundi',       bags: 0.2, type: 'A', harvest: 'Apr–Jul', notes: 'Berry, floral', fact: 'Coffee is one of its biggest exports.' },
  { id: 591, name: 'Panama',        bags: 0.1, type: 'A', harvest: 'Dec–Mar', notes: 'Jasmine, bergamot (Geisha)', fact: 'Its Geisha lots have sold for thousands of dollars per kilo at auction.' },
  { id: 887, name: 'Yemen',         bags: 0.1, type: 'A', harvest: 'Oct–Dec', notes: 'Wine, spice, dried fruit', fact: 'The port of Mocha gave the mocha its name.' },
  { id: 68,  name: 'Bolivia',       bags: 0.1, type: 'A', harvest: 'Jun–Sep', notes: 'Sweet, floral', fact: 'Some of the highest-grown coffee anywhere, over 2,000 m.' },
  { id: 388, name: 'Jamaica',       bags: 0.02,type: 'A', harvest: 'Sep–Mar', notes: 'Mild, sweet, smooth', fact: 'Blue Mountain coffee is famous, rare, and mostly bought by Japan.' },
];

// Places too small to see at world scale
export const DOT_ORIGINS = [
  { name: 'Hawaii (Kona)', lon: -155.9, lat: 19.6, fact: 'The only US state that grows coffee commercially (besides Puerto Rico, a US territory). Kona is grown on volcano slopes.' },
];

// What the giants say publicly about where their beans come from. Exact blends aren’t published
// and change every harvest, so this is the big picture, not a recipe.
export const BRANDS = [
  { id: 'starbucks', name: 'Starbucks', color: '#00704a', hq: 'Seattle', lon: -122.33, lat: 47.61,
    origins: [170, 320, 188, 76, 484, 604, 340, 231, 404, 646, 834, 360, 598, 156],
    blurb: 'All Arabica, bought from 30+ countries. It owns a research farm in Costa Rica and runs farmer support centers in places like Colombia, Rwanda, Ethiopia and Yunnan, China.',
    sold: 'Single-origins like Sumatra, Kenya, Guatemala Antigua and Ethiopia.' },
  { id: 'dunkin', name: 'Dunkin’', color: '#e11383', hq: 'Canton, MA', lon: -71.14, lat: 42.16,
    origins: [170, 76, 320, 340, 604, 558],
    blurb: 'The Original Blend is 100% Arabica from Central and South America. The exact countries change with each harvest.',
    sold: 'Medium roast built for adding milk and sugar.' },
  { id: 'tims', name: 'Tim Hortons', color: '#c8102e', hq: 'Toronto', lon: -79.38, lat: 43.65,
    origins: [170, 76, 320, 340, 604],
    blurb: '100% Arabica, mostly from Latin America. Its farmer partnership program has worked with growers in Colombia, Brazil, Guatemala and Honduras.',
    sold: 'Original Blend, medium roast.' },
  { id: 'mcd', name: 'McCafé', color: '#ffbc0d', hq: 'Chicago', lon: -87.63, lat: 41.88,
    origins: [76, 170, 320, 188, 360],
    blurb: '100% Arabica. McDonald’s has named Brazil, Colombia, Guatemala, Costa Rica and Sumatra as origins and works with Rainforest Alliance.',
    sold: 'Premium Roast, medium.' },
  { id: 'nespresso', name: 'Nespresso', color: '#8c6a43', hq: 'Lausanne', lon: 6.63, lat: 46.52,
    origins: [170, 76, 231, 404, 356, 360, 188, 320, 558, 604, 800],
    blurb: 'Owned by Nestlé. Its AAA program works with farms in about 18 countries, and some capsules mix in Robusta for crema and punch.',
    sold: 'Single-origin “Master Origins” and blends.' },
  { id: 'nescafe', name: 'Nescafé', color: '#d2232a', hq: 'Vevey', lon: 6.84, lat: 46.46,
    origins: [704, 76, 384, 360, 484, 170, 356],
    blurb: 'Nestlé is the world’s biggest coffee buyer. Instant coffee leans on Robusta, and a lot of it comes from Vietnam and Brazil.',
    sold: 'Instant coffee, 3-in-1s, Dolce Gusto.' },
];

// ---------- 06 · Grind ----------
// mm = typical particle size, flow = how fast water runs through it in the espresso machine (1 = right)
export const GRINDS = [
  { id: 'xcoarse', name: 'Extra coarse', mm: 1.6, like: 'Peppercorns', brew: ['Cold brew', 'Cowboy coffee'], time: '12–24 hours', flow: 6,
    note: 'Huge pieces extract slowly, which is perfect for a long, cold soak.' },
  { id: 'coarse', name: 'Coarse', mm: 1.1, like: 'Sea salt', brew: ['French press', 'Percolator'], time: '4 minutes', flow: 4.5,
    note: 'Big enough that the press filter catches it. Too fine and the cup gets muddy.' },
  { id: 'medcoarse', name: 'Medium-coarse', mm: 0.85, like: 'Rough sand', brew: ['Chemex', 'Clever dripper'], time: '4–5 minutes', flow: 3.4,
    note: 'Chemex filters are thick, so a slightly coarser grind keeps the flow moving.' },
  { id: 'medium', name: 'Medium', mm: 0.7, like: 'Beach sand', brew: ['Drip machine', 'Siphon'], time: '5 minutes', flow: 2.6,
    note: 'The everyday setting for an auto-drip coffee maker.' },
  { id: 'medfine', name: 'Medium-fine', mm: 0.5, like: 'Table salt', brew: ['V60 pour-over', 'AeroPress'], time: '2–3 minutes', flow: 1.7,
    note: 'Faster brews need smaller pieces so the water can catch up.' },
  { id: 'fine', name: 'Fine', mm: 0.3, like: 'Fine sugar', brew: ['Espresso', 'Moka pot'], time: '25–30 seconds', flow: 1,
    note: 'Espresso has seconds to work, so it needs a lot of surface. Tiny changes here matter a lot.' },
  { id: 'xfine', name: 'Extra fine', mm: 0.1, like: 'Flour', brew: ['Turkish coffee'], time: '3–4 minutes', flow: 0.35,
    note: 'Ground to powder and simmered in a cezve, grounds and all. Some cafés heat cezves in hot sand for slow, even heat.' },
];

// ---------- 07 · Flavor wheel ----------
// Based on the structure of the SCA / World Coffee Research flavor wheel, trimmed down.
export const FLAVORS = [
  { name: 'Floral', color: '#d9488f', about: 'Flowery aromas, usually from light roasts and high-grown, washed coffee.', find: 'Ethiopia, Panama Geisha',
    children: [{ name: 'Black tea' }, { name: 'Floral', children: ['Chamomile', 'Rose', 'Jasmine'] }] },
  { name: 'Fruity', color: '#e0412f', about: 'Bright fruit flavors. Naturals lean toward berries, washed coffees toward citrus.', find: 'Kenya, Ethiopian naturals',
    children: [
      { name: 'Berry', children: ['Blackberry', 'Raspberry', 'Blueberry', 'Strawberry'] },
      { name: 'Dried fruit', children: ['Raisin', 'Prune'] },
      { name: 'Other fruit', children: ['Coconut', 'Cherry', 'Pomegranate', 'Pineapple', 'Grape', 'Apple', 'Peach', 'Pear'] },
      { name: 'Citrus', children: ['Grapefruit', 'Orange', 'Lemon', 'Lime'] }] },
  { name: 'Sour / Fermented', color: '#e7a222', about: 'Pleasant in small doses (a winey natural), a flaw when it’s too much.', find: 'Naturals, anaerobic lots',
    children: [
      { name: 'Sour', children: ['Sour aromatics', 'Acetic acid', 'Citric acid', 'Malic acid'] },
      { name: 'Fermented', children: ['Winey', 'Whiskey', 'Overripe'] }] },
  { name: 'Green / Vegetative', color: '#5c9e3e', about: 'Fresh, grassy or raw. Often means underripe cherries or an underdeveloped roast.', find: 'Very light roasts',
    children: [{ name: 'Olive oil' }, { name: 'Raw' }, { name: 'Vegetative', children: ['Underripe', 'Peapod', 'Fresh', 'Hay-like', 'Herb-like'] }, { name: 'Beany' }] },
  { name: 'Other', color: '#3c8ea8', about: 'Mostly defects: stale, musty or chemical. Good to know so you can name what’s wrong.', find: 'Old or badly stored coffee',
    children: [
      { name: 'Papery / Musty', children: ['Stale', 'Cardboard', 'Woody', 'Musty', 'Earthy'] },
      { name: 'Chemical', children: ['Bitter', 'Salty', 'Medicinal', 'Rubber'] }] },
  { name: 'Roasted', color: '#8a5a3c', about: 'Flavors that come from the roast itself. Stronger the darker you go.', find: 'Dark roasts, Robusta',
    children: [{ name: 'Pipe tobacco' }, { name: 'Tobacco' }, { name: 'Burnt', children: ['Acrid', 'Ashy', 'Smoky', 'Brown roast'] }, { name: 'Cereal', children: ['Grain', 'Malt'] }] },
  { name: 'Spices', color: '#b2452d', about: 'Warm baking spices and pepper.', find: 'Sumatra, Guatemala, India',
    children: [{ name: 'Pungent' }, { name: 'Pepper' }, { name: 'Brown spice', children: ['Anise', 'Nutmeg', 'Cinnamon', 'Clove'] }] },
  { name: 'Nutty / Cocoa', color: '#6b3d22', about: 'The classic “coffee” flavors most people love.', find: 'Brazil, Colombia, medium roasts',
    children: [{ name: 'Nutty', children: ['Peanut', 'Hazelnut', 'Almond'] }, { name: 'Cocoa', children: ['Chocolate', 'Dark chocolate'] }] },
  { name: 'Sweet', color: '#d4782b', about: 'Sugar browning during the roast. A sweet cup is usually a well-roasted cup.', find: 'Honey process, medium roasts',
    children: [{ name: 'Brown sugar', children: ['Molasses', 'Maple syrup', 'Caramelized', 'Honey'] }, { name: 'Vanilla' }, { name: 'Overall sweet' }, { name: 'Sweet aromatics' }] },
];
